/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import App.HeadCategory;
import App.HeadCategoryTableModel;
import App.Produit;
import App.ProduitTableModel;
import App.SubCategory;
import App.SubCategoryTableModel;
import designpattern.Observateur;
import java.awt.Color;
import java.awt.Font;
import java.sql.DatabaseMetaData;
import javax.accessibility.AccessibleRole;
import javax.swing.JPanel;

/**
 *
 * @author Willy
 */
public class GUI extends javax.swing.JFrame implements Observateur{

    private Produit p;
    private HeadCategory h;
    private SubCategory s;
    private ProduitTableModel model;
    private HeadCategoryTableModel hcmodel;
    private SubCategoryTableModel scmodel;
    private int observatorPointer;
    /**
     * Creates new form GUI
     */
    public GUI() {
       initComponents();
       handleProductObservator();
       handleHeadCategoryObservator();
       handleSubCategoryObservator();
       
       StockTable.getTableHeader().setOpaque(false);
       StockTable.getTableHeader().setBackground(new Color(81,104,255));
       StockTable.getTableHeader().setForeground(new Color(255,255,255));
       StockTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
       
       model = new ProduitTableModel();
       StockTable.setModel(model);
       
       hcmodel = new HeadCategoryTableModel();
       HeadCategoriesTable.setModel(hcmodel);
       
       scmodel = new SubCategoryTableModel();
       SubCategoriesTable.setModel(scmodel);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        MainTab = new javax.swing.JTabbedPane();
        Dashboard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Stocks = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StockTable = new javax.swing.JTable();
        AddButton = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        AddProduct = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NbPdtText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        PdtNameText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        PdtPriceText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PdtQtyText = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        SubmitProduct = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        ProductCategory = new javax.swing.JComboBox<>();
        Details = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        NbProduct = new javax.swing.JLabel();
        ProductName = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ProductPrice = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ProductQty = new javax.swing.JLabel();
        DeleteProductButton = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        ProductEditButton = new javax.swing.JButton();
        Categories = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SubCategoriesTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        HeadCategoriesTable = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        headCategoryIdTxt = new javax.swing.JTextField();
        HeadCategorySubmit = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        SubCategoryIdTxt = new javax.swing.JTextField();
        SubCategorySubmit = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        HeadCategoryCbox = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        headCategoryNameTxt = new javax.swing.JTextField();
        jlabel39 = new javax.swing.JLabel();
        jlabel40 = new javax.swing.JLabel();
        SubCategoryTxt = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        EditProduct = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        NbPdtText1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        PdtNameText1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        PdtPriceText1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        PdtQtyText1 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        SubmitEditProduct = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        ProductCategorieEdit = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        DashboardMenu = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DashboardButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StocksButton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CategoriesButton = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Dashboard");
        Dashboard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        MainTab.addTab("tab1", Dashboard);

        Stocks.setBackground(new java.awt.Color(255, 255, 255));
        Stocks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Stocks");
        Stocks.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        StockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°", "Nom du produit", "Prix", "Quantité"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StockTable.setFocusable(false);
        StockTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        StockTable.setRowHeight(25);
        StockTable.setSelectionBackground(new java.awt.Color(118, 86, 255));
        StockTable.setShowVerticalLines(false);
        StockTable.getTableHeader().setReorderingAllowed(false);
        StockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StockTable);

        Stocks.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1000, 560));

        AddButton.setBackground(new java.awt.Color(55, 155, 255));
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddButtonMouseExited(evt);
            }
        });
        AddButton.setLayout(new java.awt.BorderLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        AddButton.add(jLabel10, java.awt.BorderLayout.CENTER);

        Stocks.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 40, 40));

        MainTab.addTab("tab2", Stocks);

        AddProduct.setBackground(new java.awt.Color(255, 255, 255));
        AddProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Ajout de produit");
        AddProduct.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Numéro du produit");
        AddProduct.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        AddProduct.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 700, 10));

        NbPdtText.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        NbPdtText.setBorder(null);
        AddProduct.add(NbPdtText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 700, 50));
        AddProduct.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 700, 10));

        PdtNameText.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PdtNameText.setBorder(null);
        AddProduct.add(PdtNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 700, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Nom du produit");
        AddProduct.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        AddProduct.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 700, 10));

        PdtPriceText.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PdtPriceText.setBorder(null);
        AddProduct.add(PdtPriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 700, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Prix");
        AddProduct.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Catégorie");
        AddProduct.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        PdtQtyText.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PdtQtyText.setBorder(null);
        AddProduct.add(PdtQtyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 700, 50));
        AddProduct.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 700, 10));

        SubmitProduct.setBackground(new java.awt.Color(55, 155, 255));
        SubmitProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitProductMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitProductMouseExited(evt);
            }
        });
        SubmitProduct.setLayout(new java.awt.BorderLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Ajouter");
        SubmitProduct.add(jLabel16, java.awt.BorderLayout.CENTER);

        AddProduct.add(SubmitProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 140, 40));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel40.setText("Quantité");
        AddProduct.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        AddProduct.add(ProductCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 160, 50));

        MainTab.addTab("tab3", AddProduct);

        Details.setBackground(new java.awt.Color(255, 255, 255));
        Details.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("Détails d'un produit");
        Details.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(183, 183, 183));
        jLabel19.setText("Numéro du produit");
        Details.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        NbProduct.setText("1");
        Details.add(NbProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 10, -1));

        ProductName.setText("GTX 1050 Ti");
        Details.add(ProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(183, 183, 183));
        jLabel20.setText("Nom du produit");
        Details.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(183, 183, 183));
        jLabel21.setText("Prix");
        Details.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        ProductPrice.setText("25");
        Details.add(ProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(183, 183, 183));
        jLabel22.setText("Quantité");
        Details.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        ProductQty.setText("25");
        Details.add(ProductQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        DeleteProductButton.setBackground(new java.awt.Color(118, 86, 255));
        DeleteProductButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteProductButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteProductButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteProductButtonMouseExited(evt);
            }
        });
        DeleteProductButton.setLayout(new java.awt.BorderLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Supprimer le produit");
        DeleteProductButton.add(jLabel24, java.awt.BorderLayout.CENTER);

        Details.add(DeleteProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 160, 40));

        ProductEditButton.setText("Mofidier");
        ProductEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductEditButtonMouseClicked(evt);
            }
        });
        Details.add(ProductEditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 140, 40));

        MainTab.addTab("tab4", Details);

        Categories.setBackground(new java.awt.Color(255, 255, 255));
        Categories.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel30.setText("Catégories de produit");
        Categories.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        SubCategoriesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nom de categorie"
            }
        ));
        jScrollPane2.setViewportView(SubCategoriesTable);

        Categories.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 500, 390));

        HeadCategoriesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nom de categorie"
            }
        ));
        jScrollPane3.setViewportView(HeadCategoriesTable);

        Categories.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 500, 390));

        jLabel33.setText("Sous catégories");
        Categories.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jLabel34.setText("Catégories principales");
        Categories.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel35.setText("Nouvelle catégorie principale");
        Categories.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));
        Categories.add(headCategoryIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 210, 30));

        HeadCategorySubmit.setText("Ajouter");
        HeadCategorySubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeadCategorySubmitActionPerformed(evt);
            }
        });
        Categories.add(HeadCategorySubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));

        jLabel36.setText("Sous catégorie");
        Categories.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, -1, -1));
        Categories.add(SubCategoryIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 210, 30));

        SubCategorySubmit.setText("Ajouter");
        SubCategorySubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubCategorySubmitActionPerformed(evt);
            }
        });
        Categories.add(SubCategorySubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 690, -1, -1));

        jLabel37.setText("Nouvelle sous catégorie");
        Categories.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, -1));

        Categories.add(HeadCategoryCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, 210, 30));

        jLabel38.setText("ID");
        Categories.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, -1, -1));
        Categories.add(headCategoryNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 210, 30));

        jlabel39.setText("ID");
        Categories.add(jlabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jlabel40.setText("Nom de catégorie");
        Categories.add(jlabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, -1, -1));
        Categories.add(SubCategoryTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, 210, 30));

        jLabel39.setText("Catégorie parente");
        Categories.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, -1, -1));

        MainTab.addTab("tab6", Categories);

        EditProduct.setBackground(new java.awt.Color(255, 255, 255));
        EditProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setText("Modifier un produit");
        EditProduct.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Numéro du produit");
        EditProduct.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        EditProduct.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 700, 10));

        NbPdtText1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        NbPdtText1.setBorder(null);
        EditProduct.add(NbPdtText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 700, 50));
        EditProduct.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 700, 10));

        PdtNameText1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PdtNameText1.setBorder(null);
        EditProduct.add(PdtNameText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 700, 50));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Nom du produit");
        EditProduct.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        EditProduct.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 700, 10));

        PdtPriceText1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PdtPriceText1.setBorder(null);
        EditProduct.add(PdtPriceText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 700, 50));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Prix");
        EditProduct.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Catégorie");
        EditProduct.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        PdtQtyText1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        PdtQtyText1.setBorder(null);
        EditProduct.add(PdtQtyText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 700, 50));
        EditProduct.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 700, 10));

        SubmitEditProduct.setBackground(new java.awt.Color(55, 155, 255));
        SubmitEditProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitEditProductMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitEditProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitEditProductMouseExited(evt);
            }
        });
        SubmitEditProduct.setLayout(new java.awt.BorderLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Modifier");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        SubmitEditProduct.add(jLabel29, java.awt.BorderLayout.CENTER);

        EditProduct.add(SubmitEditProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 140, 40));

        EditProduct.add(ProductCategorieEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 140, 60));
        EditProduct.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel41.setText("Quantité");
        EditProduct.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        MainTab.addTab("tab5", EditProduct);

        MainPanel.add(MainTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1071, 830));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 0, 1071, 768));

        DashboardMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(81, 104, 255));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion de stocks");
        Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        DashboardButton.setBackground(new java.awt.Color(81, 104, 255));
        DashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardButtonMouseExited(evt);
            }
        });
        DashboardButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tachometer.png"))); // NOI18N
        DashboardButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dashboard");
        DashboardButton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, 30));

        Menu.add(DashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 295, 50));

        StocksButton.setBackground(new java.awt.Color(81, 104, 255));
        StocksButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StocksButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StocksButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StocksButtonMouseExited(evt);
            }
        });
        StocksButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/stock.png"))); // NOI18N
        StocksButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stocks");
        StocksButton.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, 30));

        Menu.add(StocksButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 295, 50));

        LogoutButton.setBackground(new java.awt.Color(81, 104, 255));
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseExited(evt);
            }
        });
        LogoutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        LogoutButton.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Déconnexion");
        LogoutButton.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, 30));

        Menu.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 708, 295, 60));

        CategoriesButton.setBackground(new java.awt.Color(81, 104, 255));
        CategoriesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CategoriesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CategoriesButtonMouseExited(evt);
            }
        });
        CategoriesButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/full_screen_32px.png"))); // NOI18N
        CategoriesButton.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Catégories");
        CategoriesButton.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, 30));

        Menu.add(CategoriesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 295, 50));

        DashboardMenu.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 295, 768));

        getContentPane().add(DashboardMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 295, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changeColor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void handleProductObservator(){
        p = new Produit();
       this.p = p;
       p.ajouterObservateur(this);
    }
    
    public void handleHeadCategoryObservator(){
        h = new HeadCategory();
        this.h=h;
        h.ajouterObservateur(this);
    }
    
    public void handleSubCategoryObservator(){
        s = new SubCategory();
        this.s=s;
        s.ajouterObservateur(this);
    }
    
    public void handleRemoveProductObservator(){
       p.supprimerObservateur(this);
    }
    
    public void handleRemoveHeadCategoryObservator(){
       h.supprimerObservateur(this);
    }
    public void handleRemoveSubCategoryObservator(){
       s.supprimerObservateur(this);
    }
    
    
    private void DashboardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardButtonMouseEntered
        changeColor(DashboardButton, new Color(55,155,255));
    }//GEN-LAST:event_DashboardButtonMouseEntered

    private void DashboardButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardButtonMouseExited
        changeColor(DashboardButton, new Color(81,104,255));
    }//GEN-LAST:event_DashboardButtonMouseExited

    private void StocksButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StocksButtonMouseEntered
        changeColor(StocksButton, new Color(55,155,255));
    }//GEN-LAST:event_StocksButtonMouseEntered

    private void StocksButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StocksButtonMouseExited
        changeColor(StocksButton, new Color(81,104,255));
    }//GEN-LAST:event_StocksButtonMouseExited

    private void LogoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseEntered
        changeColor(LogoutButton, new Color(55,155,255));
    }//GEN-LAST:event_LogoutButtonMouseEntered

    private void LogoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseExited
        changeColor(LogoutButton, new Color(81,104,255));
    }//GEN-LAST:event_LogoutButtonMouseExited

    private void DashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardButtonMouseClicked
        MainTab.setSelectedIndex(0);
    }//GEN-LAST:event_DashboardButtonMouseClicked

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void StocksButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StocksButtonMouseClicked
        MainTab.setSelectedIndex(1);
    }//GEN-LAST:event_StocksButtonMouseClicked

    private void AddButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseEntered
        changeColor(AddButton, new Color(81,104,255));
    }//GEN-LAST:event_AddButtonMouseEntered

    private void AddButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseExited
        changeColor(AddButton, new Color(55,155,255));
    }//GEN-LAST:event_AddButtonMouseExited

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        handleProductObservator();
        handleRemoveHeadCategoryObservator();
        handleRemoveSubCategoryObservator();
        MainTab.setSelectedIndex(2);
    }//GEN-LAST:event_AddButtonMouseClicked

    private void SubmitProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitProductMouseExited
        changeColor(SubmitProduct, new Color(55,155,255));
    }//GEN-LAST:event_SubmitProductMouseExited

    private void SubmitProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitProductMouseEntered
        changeColor(SubmitProduct, new Color(81,104,255));
    }//GEN-LAST:event_SubmitProductMouseEntered

    private void SubmitProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitProductMouseClicked
        observatorPointer = 0;
        p.createProduct(Long.parseLong(NbPdtText.getText()), PdtNameText.getText(), Float.parseFloat(PdtPriceText.getText()), Integer.parseInt(PdtQtyText.getText()));
        MainTab.setSelectedIndex(1);
    }//GEN-LAST:event_SubmitProductMouseClicked

    private void StockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockTableMouseClicked
        handleProductObservator();
        
        int row = StockTable.getSelectedRow() ;
        NbProduct.setText(StockTable.getValueAt(row,0).toString());
        ProductName.setText(StockTable.getValueAt(row,1).toString());
        ProductPrice.setText(StockTable.getValueAt(row,2).toString());
        ProductQty.setText(StockTable.getValueAt(row,3).toString());
        MainTab.setSelectedIndex(3);
    }//GEN-LAST:event_StockTableMouseClicked

    private void DeleteProductButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteProductButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteProductButtonMouseClicked

    private void DeleteProductButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteProductButtonMouseEntered
        changeColor(DeleteProductButton, new Color(255,104,104));
    }//GEN-LAST:event_DeleteProductButtonMouseEntered

    private void DeleteProductButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteProductButtonMouseExited
        changeColor(DeleteProductButton, new Color(118,86,255));
    }//GEN-LAST:event_DeleteProductButtonMouseExited

    private void SubmitEditProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitEditProductMouseClicked
        // TODO add your handling code here:
        handleProductObservator();
        //PdtNameText1.set
    }//GEN-LAST:event_SubmitEditProductMouseClicked

    private void SubmitEditProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitEditProductMouseEntered
        changeColor(SubmitProduct, new Color(81,104,255));
    }//GEN-LAST:event_SubmitEditProductMouseEntered

    private void SubmitEditProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitEditProductMouseExited
        changeColor(SubmitProduct, new Color(55,155,255));
    }//GEN-LAST:event_SubmitEditProductMouseExited

    private void CategoriesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriesButtonMouseClicked
        handleRemoveProductObservator();
        handleHeadCategoryObservator();
        handleSubCategoryObservator();
        MainTab.setSelectedIndex(4);
    }//GEN-LAST:event_CategoriesButtonMouseClicked

    private void CategoriesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriesButtonMouseEntered
        changeColor(CategoriesButton, new Color(55,155,255));
    }//GEN-LAST:event_CategoriesButtonMouseEntered

    private void CategoriesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriesButtonMouseExited
        changeColor(CategoriesButton, new Color(81,104,255));
    }//GEN-LAST:event_CategoriesButtonMouseExited

    private void HeadCategorySubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeadCategorySubmitActionPerformed
        observatorPointer = 1;
        h.createHeadCategory(Integer.parseInt(headCategoryIdTxt.getText()),headCategoryNameTxt.getText());
    }//GEN-LAST:event_HeadCategorySubmitActionPerformed

    private void SubCategorySubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubCategorySubmitActionPerformed
        observatorPointer = 2;
        s.createSubCategory(Integer.parseInt(SubCategoryIdTxt.getText()),SubCategoryTxt.getText(), (HeadCategory)HeadCategoryCbox.getSelectedItem());
    }//GEN-LAST:event_SubCategorySubmitActionPerformed

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void ProductEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductEditButtonMouseClicked
        // TODO add your handling code here:
        NbPdtText1.setText(NbProduct.toString());
        PdtNameText1.setText(ProductName.toString());
        PdtPriceText1.setText(ProductPrice.toString());
        PdtQtyText1.setText(ProductQty.toString());
        MainTab.setSelectedIndex(5);
    }//GEN-LAST:event_ProductEditButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddButton;
    private javax.swing.JPanel AddProduct;
    private javax.swing.JPanel Categories;
    private javax.swing.JPanel CategoriesButton;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel DashboardButton;
    private javax.swing.JPanel DashboardMenu;
    private javax.swing.JPanel DeleteProductButton;
    private javax.swing.JPanel Details;
    private javax.swing.JPanel EditProduct;
    private javax.swing.JTable HeadCategoriesTable;
    private javax.swing.JComboBox<HeadCategory> HeadCategoryCbox;
    private javax.swing.JButton HeadCategorySubmit;
    private javax.swing.JPanel LogoutButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JPanel Menu;
    private javax.swing.JTextField NbPdtText;
    private javax.swing.JTextField NbPdtText1;
    private javax.swing.JLabel NbProduct;
    private javax.swing.JTextField PdtNameText;
    private javax.swing.JTextField PdtNameText1;
    private javax.swing.JTextField PdtPriceText;
    private javax.swing.JTextField PdtPriceText1;
    private javax.swing.JTextField PdtQtyText;
    private javax.swing.JTextField PdtQtyText1;
    private javax.swing.JComboBox<SubCategory> ProductCategorieEdit;
    private javax.swing.JComboBox<SubCategory> ProductCategory;
    private javax.swing.JButton ProductEditButton;
    private javax.swing.JLabel ProductName;
    private javax.swing.JLabel ProductPrice;
    private javax.swing.JLabel ProductQty;
    private javax.swing.JTable StockTable;
    private javax.swing.JPanel Stocks;
    private javax.swing.JPanel StocksButton;
    private javax.swing.JTable SubCategoriesTable;
    private javax.swing.JTextField SubCategoryIdTxt;
    private javax.swing.JButton SubCategorySubmit;
    private javax.swing.JTextField SubCategoryTxt;
    private javax.swing.JPanel SubmitEditProduct;
    private javax.swing.JPanel SubmitProduct;
    private javax.swing.JTextField headCategoryIdTxt;
    private javax.swing.JTextField headCategoryNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jlabel39;
    private javax.swing.JLabel jlabel40;
    // End of variables declaration//GEN-END:variables

    @Override
    public void notifier(Object o) {
        switch(observatorPointer)
        {
            case 0:
                model.addProduit((Produit) o);
                break;
            case 1:
                hcmodel.addCategory((HeadCategory) o);
                HeadCategoryCbox.addItem((HeadCategory)o);
                handleHeadCategoryObservator();
                break;
            case 2:
                scmodel.addCategory((SubCategory) o);
                ProductCategory.addItem((SubCategory)o);
                ProductCategorieEdit.addItem((SubCategory)o);
                handleSubCategoryObservator();
                break;
            default:
                System.out.println("No matching pointer");
           
        }
    }
}
